import React from "react";
import LoginForm from "../components/LoginForm";
import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>chatApp Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LoginForm />;
    </>
  );
}

export default Home;
